name: Build and Test

on: [push, pull_request]

jobs:

  test-win:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: '**/*.nupkg'